title: Donovan Palmer
email: donovan@donovanpalmer.net
url: "http://www.donovanpalmer.net"
baseurl: /dgpalmer.github.io

plugins:
  - jekyll-postcss

sass:
  load_paths:
    - _sass
    - node_modules

include: ["node_modules/tailwindcss"]
